# Generated by Django 5.2.9 on 2025-12-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('technologies', models.JSONField(default=list, help_text='List of technologies used')),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('notebook_url', models.URLField(blank=True, help_text='Link to Colab/Kaggle notebook')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
